# Generated by Django 5.0.1 on 2024-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='question1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question9',
            field=models.IntegerField(default=0),
        ),
    ]
