# Generated by Django 5.0.1 on 2024-03-06 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userresponse_delete_quizresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='QuizResponse',
        ),
    ]
